language: node_js
node_js:
  - '9'
sudo: false
before_install: sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev librsvg2-dev build-essential g++ && npm i install canvas@2.0.0-alpha.11
script:
  - 'npm test'
after_success:
  - 'npm install coveralls && ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
  